apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-external-secrets-operator-test2
  annotations:
    argocd.argoproj.io/sync-wave: 30
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-3
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator
            namespace: external-secrets-operator
