apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <namespace>
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: <cluster-name>
  source:
    repoURL: <repo>
    targetRevision: <chart-version>
    chart: <chart-name>
  destination:
    name: <cluster-name>
    namespace: <namespace>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
