{{- if .Values.serviceAccount.createClusterRoleBindings -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-secret-access-binding
  namespace: {{ .Values.serviceAccount.namespace }}  # Namespace where the RoleBinding is created
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.serviceAccount.namespace }}
roleRef:
  kind: Role
  name: secret-access
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
