{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access
  namespace: {{ .Values.serviceAccount.namespace }}  
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "update"]
{{- end -}}
